version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
