version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/main
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/usr/src/main
    working_dir: /usr/src/main
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
